Styling
hack4impact/maps4all-jlc-sp2 pull request #2
Opened 2016-12-11 20:17 UTC by stephanieyshi

- font styling
- colors
- spacing

<img width="1434" alt="screen shot 2016-12-11 at 3 16 19 pm" src="https://cloud.githubusercontent.com/assets/20306315/21082967/d7ea5a18-bfb4-11e6-8c6c-5e532f66f74b.png">
<img width="1429" alt="screen shot 2016-12-11 at 3 16 11 pm" src="https://cloud.githubusercontent.com/assets/20306315/21082972/d7edd1b6-bfb4-11e6-95ff-ee2b11ddaa8d.png">
<img width="1055" alt="screen shot 2016-12-11 at 3 15 52 pm" src="https://cloud.githubusercontent.com/assets/20306315/21082970/d7eae7bc-bfb4-11e6-8ad7-34bbc72242f9.png">
<img width="1057" alt="screen shot 2016-12-11 at 3 15 47 pm" src="https://cloud.githubusercontent.com/assets/20306315/21082969/d7eae2bc-bfb4-11e6-80bd-3a4737450c83.png">
<img width="1435" alt="screen shot 2016-12-11 at 3 15 39 pm" src="https://cloud.githubusercontent.com/assets/20306315/21082968/d7ead678-bfb4-11e6-9b45-7c49b8804202.png">
<img width="1433" alt="screen shot 2016-12-11 at 3 15 32 pm" src="https://cloud.githubusercontent.com/assets/20306315/21082971/d7eb6854-bfb4-11e6-8d51-10b9da7f08eb.png">

2016-12-11 20:47 UTC, anniemeng requested changes
also in general I see many diff elements where you set the font family property - are these necessary if we have the body ones? or are they overridden somehow by semantic ui or other styles?

2016-12-11 20:47 UTC, anniemeng commented on app/assets/scripts/map.js
> +    $("list-specific-resource").css("background-color", "yellow");
this doesn't currently work right? let's remove this

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/admin.scss
> +#admin-home {
nit: alphabetize

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/app.scss
> +    font-family: $font-choice!important;
is there anyway to avoid `!important`?

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/map.scss
> +    margin-left: -2px;
is there a way to avoid negative here

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/map.scss
> +  margin-left: -2px;
same about negative?

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/app.scss
> +  font-family: 'Nunito Sans', sans-serif;
use `$font-choice` variable

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/user.scss
> +#about, #suggest-resource, #contact, #login, #reset-password, #health, #rights {
can you add a general class instead and style that one class and add it to the divs with these ids?

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/user.scss
> +#about, #suggest-resource, #contact, #login, #reset-password, #health, #rights {
also alphabetize these styles

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/user.scss
> +#about, #health, #rights {
same thing about adding making a general class instead of listing ids - maybe something relating to static pages like `.static-page`

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/user.scss
> +#about-header, #health-header, #rights-header {
same thing about class

2016-12-11 20:47 UTC, anniemeng commented on app/assets/styles/user.scss
> +#suggest-resource, #contact, #login {
same thing about class

2016-12-11 20:47 UTC, anniemeng commented on app/templates/contact/index.html
> +            <!--<div class="ui divider"></div>-->
we want to keep this divider since we'll have text above the contact form and we need to make it seem separate

2016-12-11 20:47 UTC, anniemeng commented on app/templates/main/index.html
> +  <div class="item list-resource" id="list-specific-resource">
we can also remove this once we remove the style

2016-12-11 20:47 UTC, anniemeng commented on app/templates/suggestion/suggest.html
> +    <!--<a class="ui basic compact button" href="{{ url_for('main.index') }}">
we can just delete this button

2016-12-11 23:31 UTC, stephanieyshi commented on app/assets/styles/app.scss
> +    font-family: $font-choice!important;
I've tried it without !important and the font isn't consistently changed

2016-12-12 01:32 UTC, anniemeng approved these changes
:tada:

2016-12-12 01:35 UTC, merged